server:
  port: 81
  tomcat:
    uri-encoding: UTF-8

spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  datasource:
    url: jdbc:mariadb://localhost:3308/MusicQTest
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 8236

  # Oauth2 Setting
  security:
    oauth2:
      client:
        registration:

          kakao:
            client-id: 38f43ff5aee9ea89cc35c4503953906c
            client-secret: EnGcSiLEKbQlwNn9x11BxXZzlsEspMDq
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  header: Authorization
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  access-token-validity-in-seconds: 86400
  refresh-token-validity-in-seconds: 604800


logging:
  level:
    com.kakao: DEBUG

app:
  oauth2:
    authorizedRedirectUri: "http://localhost/auth/token"